export const FORM_TASK_CHANGE = "FORM_TASK_CHANGE";
export const FORM_FILTER_CHANGE = "FORM_FILTER_CHANGE";
export const CLEAR_FORM = "CLEAR_FORM";
export const TASK_CREATE = "TASK_CREATE";
export const TASK_DELETE = "TASK_DELETE";
export const TASK_UPDATE = "TASK_UPDATE";
export const SWITCH_EDIT_MODE = "SWITCH_EDIT_MODE";